"""Post-incident report export (Markdown)."""

from datetime import datetime, timezone
from pathlib import Path

from incident_commander.models.incident import Incident


def export_postmortem_markdown(incident: Incident) -> str:
    lines: list[str] = []
    lines.append(f"# Post-incident report: {incident.incident_id}")
    lines.append("")
    lines.append(f"- **Service:** {incident.service}")
    lines.append(f"- **Namespace:** {incident.namespace}")
    lines.append(f"- **Status:** {incident.status.value}")
    lines.append(f"- **Severity:** {incident.severity}")
    lines.append(f"- **Trigger:** {incident.trigger}")
    lines.append(f"- **Opened:** {incident.opened_at.isoformat()}")
    if incident.resolved_at:
        lines.append(f"- **Resolved:** {incident.resolved_at.isoformat()}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(incident.summary or "_No summary recorded._")
    lines.append("")

    if incident.timeline:
        lines.append("## Timeline")
        lines.append("")
        for event in incident.timeline:
            lines.append(
                f"- `{event.at.isoformat()}` **{event.source}** ({event.confidence}): {event.event}"
            )
        lines.append("")

    if incident.worker_runs:
        lines.append("## Worker runs")
        lines.append("")
        lines.append("| Worker | Status | Summary |")
        lines.append("|--------|--------|---------|")
        for run in incident.worker_runs:
            summary = run.summary.replace("|", "\\|")[:120]
            lines.append(f"| {run.worker} | {run.status} | {summary} |")
        lines.append("")

    if incident.hypotheses:
        lines.append("## Hypotheses")
        lines.append("")
        for hyp in incident.hypotheses:
            lines.append(f"### {hyp.id} ({hyp.confidence:.0%} confidence)")
            lines.append("")
            lines.append(hyp.description)
            lines.append("")
            if hyp.suggested_actions:
                lines.append("**Suggested actions:**")
                for action in hyp.suggested_actions:
                    lines.append(
                        f"- `{action.type}` ({action.risk.value}): {action.description}"
                    )
                lines.append("")

    if incident.approvals_pending:
        lines.append("## Pending approvals")
        lines.append("")
        for approval in incident.approvals_pending:
            lines.append(
                f"- `{approval.id}` — {approval.action.type}: {approval.action.description}"
            )
        lines.append("")

    if incident.llm_usage and incident.llm_usage.calls > 0:
        lines.append("## LLM usage")
        lines.append("")
        lines.append(
            f"- **Calls:** {incident.llm_usage.calls}"
        )
        lines.append(
            f"- **Tokens:** {incident.llm_usage.total_tokens} "
            f"(prompt {incident.llm_usage.prompt_tokens}, "
            f"completion {incident.llm_usage.completion_tokens})"
        )
        lines.append(
            f"- **Estimated cost:** ${incident.llm_usage.estimated_cost_usd:.4f} USD"
        )
        lines.append("")

    lines.append("---")
    lines.append(
        f"_Generated by Incident Commander at {datetime.now(timezone.utc).isoformat()}_"
    )
    lines.append("")
    return "\n".join(lines)


def write_postmortem_markdown(incident: Incident, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(export_postmortem_markdown(incident), encoding="utf-8")
    return path
